version: '3.8'


services:
  postgres:
    container_name: postgres_todo
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: super_admin
      POSTGRES_PASSWORD: 12345678
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"


volumes:
  postgres-db:
    driver: local